### ISSUE TITLE
Cron issues

### ISSUE THREAD

**Issue by wtdewilligen** [wtdewilligen/EVE-Online-POS-Tracker#2]
When any of the cron scripts are ran, it throws exceptions and fail to run.

**Comment by i420bdawg** [comment]
I managed to get Crons work but it broke the POS Tracking Page to where it throws this error: 
Warning: Missing argument 1 for POSMGMT::GetAllPos2(), called in /home/*/public_html/postracker/track.php on line 96 and defined in /home/*/public_html/postracker/includes/class.pos.php on line 934

**Comment by wtdewilligen** [comment]
What did you do to get the cron to work?

**Comment by i420bdawg** [comment]
I am writing my notes up now... i will share shortly

**Comment by i420bdawg** [comment]
i fixed my own issue.  as well as traced down the exact change that fixed cron. THis change allows it to work with PHP 5.2, 5.3 and 5.4

includes/dbfunctions.php 
replace line 22:

   Original Code:
   ```      error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING);```

   Updated Code:
```      if(phpversion() >= '5.3.0')
                        {
                                error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT & ~E_WARNING);
                        }
                        else
                        {
                                error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT & ~E_WARNING);
                        }```

**Comment by i420bdawg** [comment]
on top of that i use a custom SH Script for my cron as I have muiltiple hourly scripts to run.  below is an example of my SH Script and the command to run in in cpanel cron.

CPanel Cron Command:
```
/bin/sh /home/{username}/cron/Hourly.sh
```

Hourly.sh (Changed for POS Tracker Only)
```
#!/bin/sh

: 'POS Tracker Hourly Scripts'
php -q ./public_html/postracker/cron_updatepos.php
```

**Comment by i420bdawg** [comment]
Please let me know if my solution worked for you.

**Comment by wtdewilligen** [comment]
I will try and take a look at it today.

**Comment by wtdewilligen** [comment]
It looks like it is running the cron right. I went and updated the crons php file location as well. I have made changes to the testing branch.

**Comment by i420bdawg** [comment]
sweet, glad it helped
